export type Project = { slug:string; title:string; category:string; date:string; description:string; overview:string; challenge:string; solution:string; technologies:string[]; image?:string; github?:string; featured?:boolean };
export const projects: Project[] = [
 {slug:"branded-cosmetics",title:"BRANCY Cosmetics",category:"Full-stack commerce",date:"2024",description:"A complete cosmetics shopping experience with catalog, cart, checkout, invoices, accounts, and administration.",overview:"A Django commerce platform designed for a branded cosmetics business.",challenge:"Make product discovery and purchasing trustworthy, simple, and manageable from one place.",solution:"Built customer and administrator workflows end to end, backed by Django and a relational data model.",technologies:["Django","Python","JavaScript","HTML/CSS"],image:"/portfolio/brancy.png",github:"https://github.com/khinmyatthu2193/brancy-branded-cosmetics-onlineshopping-system",featured:true},
 {slug:"recyclelink",title:"RecycleLink",category:"Real-time web platform",date:"2025",description:"A recycling coordination platform with location-based supplier alerts and live collection updates.",overview:"A platform connecting recycling activity to nearby suppliers.",challenge:"Fragmented communication makes collection updates stale.",solution:"Used proximity matching, WebSockets, and Django Channels for synchronized updates.",technologies:["Django Channels","WebSockets","PostgreSQL"],featured:true},
 {slug:"climbio",title:"Climbio",category:"Mobile business toolkit",date:"2025",description:"A mobile-first MSME toolkit combining catalogs, customer conversations, and referral tracking.",overview:"Practical digital workflows for small and medium businesses.",challenge:"Business owners manage customers and products across disconnected tools.",solution:"Combined MiniCatalog, Smart Inbox, and referral tools in one approachable app.",technologies:["React Native","Firebase","JavaScript"],featured:true},
 {slug:"career-ladder",title:"Career Ladder",category:"AI product",date:"2025",description:"Personalized career recommendations, learning paths, and job insights organized into a clear roadmap.",overview:"A career exploration product shaped around each learner.",challenge:"Generic career advice rarely offers a useful sequence of next steps.",solution:"Designed an AI recommendation flow that turns context into an understandable roadmap.",technologies:["AI","Recommendation Systems","Web"],featured:true},
 {slug:"future-harvest",title:"Future Harvest",category:"Climate innovation",date:"2025",description:"A sustainable agriculture concept focused on food security and climate resilience.",overview:"Accessible technology supporting resilient food production.",challenge:"Farming systems face increasing climate pressure.",solution:"Proposed SMNR-assisted information and climate-resilient decisions.",technologies:["AgriTech","Sustainability","Innovation"]},
 {slug:"strivo",title:"Strivo",category:"AI mobile app",date:"2026",description:"An AI planning assistant helping MSMEs produce structured strategies and recommendations.",overview:"Approachable strategic planning for small-business owners.",challenge:"Formal strategy frameworks can feel complex and time-consuming.",solution:"Built a guided Gemini-powered mobile flow with actionable outputs.",technologies:["React Native","Gemini AI","TypeScript"]}
];
